verion: 3.9
services:
    docker-registry:
        image: "registry:2"
        ports:
            - "5000"
        environment:
            REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
            REGISTRY_HTTP_TLS_CERTIFICATE: "./docker-registry-cert.pem"
            REGISTRY_HTTP_TLS_KEY: "./docker-registry-key.pem"
        volumes:
            - "./data:/var/lib/registry"
        restart: "on-failure"
